# Generated by Django 2.0.6 on 2018-09-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_disciplinaofertada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisciplinaOfertada',
        ),
    ]
