# Generated by Django 2.0.6 on 2018-09-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_delete_disciplinaofertada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='nome',
            new_name='nomeDisciplina',
        ),
    ]
