# Generated by Django 2.0.6 on 2018-09-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_auto_20180910_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='nomeDisciplina',
            new_name='nome',
        ),
    ]
