create table DicOfert
(
	ID_Diciplina_ofertada INT IDENTITY PRIMARY KEY NOT NULL,
	DT_INICIO_MATRICULA DATE,
	DT_FIM_MATRICULA DATE,
	ANO INT NOT NULL,
	SEMESTRE INT,
	TURMA CHAR NOT NULL,
	METODOLOGIA VARCHAR(255),
	RECURSOS varchar(155),
	CRITERIO_AVALI VARCHAR(255),
	PLANO_DE_AULAS CHAR,
	CONSTRAINT CHK_DicOfert1 Check (ANO <= 1900),
	CONSTRAINT CHK_DicOfert2 Check (ANO >= 2100),
	CONSTRAINT CHK_DicOfert3 Check (TURMA <= 'Z' AND TURMA >= 'A'),
	CONSTRAINT CHK_DicOfert4 Check (SEMESTRE <= 1),
	CONSTRAINT CHK_DicOfert5 Check (SEMESTRE >=2),
);	

create table Curso
(
	ID_curso INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_CURSO varchar(30),
	CONSTRAINT UC_Curso UNIQUE(NOME_CURSO)
);






