CREATE TABLE Aluno (
	IDALUNO INT IDENTITY  NOT NULL,
	ID_USUARIO INT   NOT NULL,
	CELULAR CHAR (9) NOT NULL UNIQUE,
	NOME VARCHAR (50) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL UNIQUE,
	FOTO VARCHAR (100) NULL,

	CONSTRAINT IDALUNO PRIMARY KEY (IDALUNO)
);



CREATE TABLE Professor (
	IDPROFESSOR INT IDENTITY  NOT NULL,
	ID_USUARIO INT   NOT NULL,
	EMAIL VARCHAR (100) NOT NULL UNIQUE,
	CELULAR CHAR (9) NOT NULL UNIQUE,
	APELIDO VARCHAR (50)

	CONSTRAINT IDPROFESSOR PRIMARY KEY (IDPROFESSOR)
);

 CREATE TABLE Entrega (
	IDENTREGA INT IDENTITY NOT NULL, 
	ID_ATIVIDADE_VINCULADA INT  NOT NULL,
	TITULO VARCHAR (50) NOT NULL,
	RESPOSTA VARCHAR (50) NOT NULL,
	DTENTREGA DATETIME DEFAULT GETDATE() NOT NULL,
	STATUS1 VARCHAR (10) DEFAULT 'ENTREGUE'NOT NULL, 
	NOTA DECIMAL (5,2) NULL,
	IDPROFESSOR INT  NULL,   
	DTAVALIACAO DATE NULL,
	OBS VARCHAR (150) NULL,
	
	CONSTRAINT IDENTREGA PRIMARY KEY (IDENTREGA),
	CHECK (STATUS1 IN ('ENTREGUE','CORRIGIDO')),
	CHECK (NOTA >=0 AND NOTA <=10)
	
);	 

