CREATE TABLE Atividade(
	ID	INT IDENTITY NOT NULL,
	TITULO VARCHAR (60) NOT NULL UNIQUE,
	DESCRIÇÃO VARCHAR(200),
	CONTEUDO CHAR NOT NULL,
	TIPO VARCHAR(16) NOT NULL CHECK(TIPO ='Resposta Aberta' or TIPO ='Teste'),
	EXTRAS VARCHAR(200),
	IDPROFESSOR INT
);

CREATE TABLE AtividadeVinculada(
	ID INT IDENTITY NOT NULL,
	IDATIVIDADE INT  NOT NULL,
	IDPROFESSOR INT  NOT NULL,
	IDDISCIPLINAOFERTADA INT  NOT NULL,
	ROTULO VARCHAR(150) NOT NULL,
	_STATUS VARCHAR(30) NOT NULL CHECK(_STATUS='Disponibilizada' or _STATUS='Aberta' or _STATUS ='Fechada') NOT NULL,
	DTINICIORESPOSTAS DATETIME NOT NULL, 
	DTFIMRESPOSTAS DATETIME NOT NULL
);